export const scheduleData = [
  {
    className: "10A1",
    subjectName: "Toán",
    teacherName: "Nguyễn Văn A",
    dayOfWeek: "Thứ Hai",
    shift: "Sáng",
    period: 1,
  },
  {
    className: "10A2",
    subjectName: "Văn",
    teacherName: "Nguyễn Văn A",
    dayOfWeek: "Thứ Ba",
    shift: "Chiều",
    period: 2,
  },
  {
    className: "10A3",
    subjectName: "Anh",
    teacherName: "Nguyễn Văn A",
    dayOfWeek: "Thứ Tư",
    shift: "Sáng",
    period: 3,
  },
  {
    className: "10A4",
    subjectName: "Lý",
    teacherName: "Nguyễn Văn A",
    dayOfWeek: "Thứ Năm",
    shift: "Chiều",
    period: 1,
  },
  {
    className: "10A5",
    subjectName: "Hóa",
    teacherName: "Nguyễn Văn A",
    dayOfWeek: "Thứ Sáu",
    shift: "Sáng",
    period: 5,
  },
  {
    className: "10A6",
    subjectName: "Sinh",
    teacherName: "Nguyễn Văn A",
    dayOfWeek: "Thứ Bảy",
    shift: "Chiều",
    period: 1,
  },
  {
    className: "10A7",
    subjectName: "Sử",
    teacherName: "Nguyễn Văn A",
    dayOfWeek: "Chủ Nhật",
    shift: "Sáng",
    period: 4,
  },
  {
    className: "10A8",
    subjectName: "Địa",
    teacherName: "Nguyễn Văn A",
    dayOfWeek: "Thứ Hai",
    shift: "Chiều",
    period: 2,
  },
  {
    className: "10A9",
    subjectName: "GDCD",
    teacherName: "Nguyễn Văn A",
    dayOfWeek: "Thứ Ba",
    shift: "Sáng",
    period: 5,
  },
  {
    className: "10A10",
    subjectName: "Công Nghệ",
    teacherName: "Nguyễn aaaa",
    dayOfWeek: "Thứ Tư",
    shift: "Chiều",
    period: 2,
  },
  {
    className: "10A1",
    subjectName: "Toán",
    teacherName: "Nguyễn aaaa",
    dayOfWeek: "Thứ Hai",
    shift: "Sáng",
    period: 1,
  },
  {
    className: "10A2",
    subjectName: "Văn",
    teacherName: "Nguyễn aaaa",
    dayOfWeek: "Thứ Ba",
    shift: "Chiều",
    period: 2,
  },
  {
    className: "10A3",
    subjectName: "Anh",
    teacherName: "Nguyễn aaaa",
    dayOfWeek: "Thứ Tư",
    shift: "Sáng",
    period: 3,
  },
];
